"""
DDB file writer for ABINIT Derivative Database files.

This module writes DDB files from UnitcellData structures,
matching the Fortran output format for round-trip compatibility.
"""

from __future__ import annotations

import numpy as np
from pathlib import Path
from typing import Optional

from .datastructures import UnitcellData


def write_ddb(filename: str, unitcell: UnitcellData):
    """
    Write UnitcellData to DDB file format.
    
    Parameters
    ----------
    filename : str
        Output DDB file path.
    unitcell : UnitcellData
        Unitcell data to write.
    
    Examples
    --------
    >>> from pymultibinit.pyeffpot import read_ddb, write_ddb
    >>> unitcell = read_ddb("input.DDB")
    >>> write_ddb("output.DDB", unitcell)
    """
    lines = []
    
    # Header
    lines.append("Generated by pymultibinit.pyeffpot")
    lines.append("")
    
    # Basic dimensions
    crystal = unitcell.crystal
    lines.append(f" natom   {crystal.natom}")
    lines.append(f" ntypat  {crystal.ntypat}")
    lines.append("")
    
    # Lattice
    acell = unitcell.acell if unitcell.acell is not None else np.diag(crystal.rprimd)
    lines.append(f" acell   {acell[0]:.14E}  {acell[1]:.14E}  {acell[2]:.14E}")
    
    # rprim
    rprim = crystal.rprimd / acell[:, np.newaxis] if unitcell.acell is not None else crystal.rprimd
    lines.append(f" rprim   {rprim[0,0]:.14E}  {rprim[0,1]:.14E}  {rprim[0,2]:.14E}")
    lines.append(f"         {rprim[1,0]:.14E}  {rprim[1,1]:.14E}  {rprim[1,2]:.14E}")
    lines.append(f"         {rprim[2,0]:.14E}  {rprim[2,1]:.14E}  {rprim[2,2]:.14E}")
    lines.append("")
    
    # Atomic masses
    amu = crystal.amu
    amu_str = "  ".join([f"{m:.14E}" for m in amu])
    lines.append(f" amu   {amu_str}")
    lines.append("")
    
    # Atomic positions
    lines.append(" xred")
    for i in range(crystal.natom):
        xred_i = crystal.xred[i]
        lines.append(f"        {xred_i[0]:.14E}  {xred_i[1]:.14E}  {xred_i[2]:.14E}")
    lines.append("")
    
    # Atom types
    typat_str = "   ".join([f"{t}" for t in crystal.typat])
    lines.append(f" typat  {typat_str}")
    lines.append("")
    
    # Atomic numbers
    znucl_str = "   ".join([f"{z:.1f}" for z in crystal.znucl])
    lines.append(f" znucl  {znucl_str}")
    lines.append("")
    
    # Energy
    if unitcell.energy != 0:
        lines.append(f" etotal  {unitcell.energy:.14E}")
        lines.append("")
    
    # Dielectric tensor
    if unitcell.epsilon_inf is not None and not np.allclose(unitcell.epsilon_inf, np.eye(3)):
        lines.append(" Dielectric tensor")
        for i in range(3):
            row = unitcell.epsilon_inf[i]
            lines.append(f"  {row[0]:.14E}  {row[1]:.14E}  {row[2]:.14E}")
        lines.append("")
    
    # Born effective charges
    if unitcell.zeff is not None and np.linalg.norm(unitcell.zeff) > 1e-10:
        lines.append(" Born effective charges")
        for iatom in range(crystal.natom):
            lines.append(f"  Atom {iatom + 1}")
            for i in range(3):
                row = unitcell.zeff[i, :, iatom]
                lines.append(f"    {row[0]:.14E}  {row[1]:.14E}  {row[2]:.14E}")
        lines.append("")
    
    # IFCs (simplified - only Gamma point)
    if unitcell.ifcs is not None:
        lines.append(" **** Database of total energy derivatives ****")
        lines.append(f" Number of data blocks=   1")
        lines.append("")
        
        # Write one block for Gamma-point IFCs
        natom = crystal.natom
        lines.append(f"  2nd derivatives (non-stationary)  # elements    :   {natom * natom * 9}")
        lines.append(f"    0.00000000E+00  0.00000000E+00")
        lines.append("")
        
        # Write IFC elements (simplified format)
        phi = unitcell.ifcs.atmfrc[:, :, :, :, 0]  # (3, natom, 3, natom)
        for i in range(natom):
            for j in range(natom):
                for mu in range(3):
                    for nu in range(3):
                        val = phi[mu, i, nu, j]
                        if abs(val) > 1e-15:
                            lines.append(f"  {mu+1}  {i+1}  {nu+1}  {j+1}  {val:.14E}  0.00000000E+00")
    
    # Write to file
    with open(filename, 'w') as f:
        f.write('\n'.join(lines))
        f.write('\n')


__all__ = ['write_ddb']
