"""Phonopy construction from analytic MULTIBINIT force constants."""

from __future__ import annotations

from importlib import import_module
from typing import TYPE_CHECKING, Any

import numpy as np

if TYPE_CHECKING:
    from ase import Atoms
    from phonopy import Phonopy

    from .calculator import MultibinitCalculator


# Keep importing pymultibinit independent of phonopy. This is phonopy's default
# eV/Angstrom^2-to-THz conversion factor.
VaspToTHz = 15.633302300230191


def calculate_analytic_phonon(
    atoms: "Atoms",
    calculator: "MultibinitCalculator",
    supercell_matrix: Any = np.eye(3),
    primitive_matrix: Any = np.eye(3),
    factor: float = VaspToTHz,
    symprec: float = 1e-5,
) -> "Phonopy":
    """Build a Phonopy object using the calculator's analytic energy Hessian.

    The calculator is evaluated on the exact atom order generated by phonopy.
    Its ``(3N, 3N)`` energy Hessian, in eV/Angstrom^2, is installed as full
    ``(N, N, 3, 3)`` force constants without a sign change.
    """
    supercell_matrix = _matrix_3x3("supercell_matrix", supercell_matrix)
    primitive_matrix = _matrix_3x3("primitive_matrix", primitive_matrix)

    get_analytic_blocks = getattr(calculator, "get_analytic_blocks", None)
    if not callable(get_analytic_blocks):
        raise TypeError("calculator must provide a callable get_analytic_blocks(atoms)")

    Phonopy, PhonopyAtoms, ASEAtoms = _import_phonon_dependencies()
    unitcell = PhonopyAtoms(
        numbers=atoms.get_atomic_numbers(),
        masses=atoms.get_masses(),
        magnetic_moments=_initial_magnetic_moments(atoms),
        cell=atoms.get_cell().array,
        scaled_positions=atoms.get_scaled_positions(),
    )
    phonon = Phonopy(
        unitcell,
        supercell_matrix=supercell_matrix,
        primitive_matrix=primitive_matrix,
        factor=factor,
        symprec=symprec,
    )

    phonopy_supercell = phonon.supercell
    analytic_atoms = ASEAtoms(
        numbers=phonopy_supercell.numbers,
        cell=phonopy_supercell.cell,
        scaled_positions=phonopy_supercell.scaled_positions,
        pbc=True,
    )
    analytic_atoms.set_masses(phonopy_supercell.masses)
    if phonopy_supercell.magnetic_moments is not None:
        analytic_atoms.set_initial_magnetic_moments(
            phonopy_supercell.magnetic_moments
        )

    blocks = get_analytic_blocks(analytic_atoms)
    ifc = np.asarray(getattr(blocks, "ifc", None))
    natom = len(phonopy_supercell)
    expected_shape = (3 * natom, 3 * natom)
    if ifc.shape != expected_shape:
        raise ValueError(
            "calculator analytic IFC matrix has shape "
            f"{ifc.shape}; expected {expected_shape} for {natom} atoms"
        )

    phonon.force_constants = ifc.reshape(natom, 3, natom, 3).transpose(0, 2, 1, 3)
    return phonon


def _matrix_3x3(name: str, matrix: Any) -> np.ndarray:
    array = np.asarray(matrix)
    if array.shape != (3, 3):
        raise ValueError(f"{name} must have shape (3, 3), got {array.shape}")
    return array


def _initial_magnetic_moments(atoms: "Atoms") -> np.ndarray | None:
    if not atoms.has("initial_magmoms"):
        return None
    moments = np.asarray(atoms.get_initial_magnetic_moments())
    if moments.shape not in ((len(atoms),), (len(atoms), 3)):
        return None
    return moments


def _import_phonon_dependencies():
    try:
        phonopy_module = import_module("phonopy")
        phonopy_atoms_module = import_module("phonopy.structure.atoms")
        ase_module = import_module("ase")
    except ImportError as exc:
        raise ImportError(
            "calculate_analytic_phonon requires phonopy and ASE"
        ) from exc
    return (
        phonopy_module.Phonopy,
        phonopy_atoms_module.PhonopyAtoms,
        ase_module.Atoms,
    )
